#!/usr/bin/env python3
# =====
import os
import json
import requests
from datetime import datetime
from openai import OpenAI
from config import Config
# =====

# =====
# אתחול הלקוח של OpenAI
client = OpenAI(
    base_url=Config.BASE_URL,
    api_key=Config.OPENAI_API_KEY,
    default_headers={
        "HTTP-Referer": "https://github.com/RootProject",
        "X-Title": "Root Agentic OS",
    }
)
# =====

# =====
def create_github_issue(title, body, labels=None):
    """יוצר Issue בגיטהאב. תומך בתוויות דינמיות למשימות שונות"""
    if not Config.GITHUB_TOKEN or not Config.GITHUB_REPOSITORY:
        print("⚠️ [GitHub API] Missing credentials, skipping issue creation.")
        return

    if labels is None:
        labels = ["root-critic", "automated"]

    url = f"https://api.github.com/repos/{Config.GITHUB_REPOSITORY}/issues"
    headers = {
        "Authorization": f"token {Config.GITHUB_TOKEN}",
        "Accept": "application/vnd.github.v3+json"
    }
    data = {"title": title, "body": body, "labels": labels}
    
    try:
        response = requests.post(url, json=data, headers=headers)
        if response.status_code == 201:
            print(f"📢 [Root] GitHub Issue created: {response.json().get('html_url')}")
        else:
            print(f"❌ [GitHub API] Failed: {response.status_code}")
    except Exception as e:
        print(f"❌ [GitHub API] Connection error: {e}")
# =====

# =====
def update_roadmap(new_tasks):
    """ניהול ה-ROADMAP.md: מוסיף משימות חדשות מבלי למחוק את הקיימות"""
    roadmap_file = "ROADMAP.md"
    now = datetime.now().strftime("%d/%m/%Y")
    
    # 1. קריאת המצב הקיים כדי לא ליצור כפילויות
    existing_content = ""
    if os.path.exists(roadmap_file):
        with open(roadmap_file, "r", encoding="utf-8") as f:
            existing_content = f.read()
    else:
        existing_content = "# 🗺️ Root Strategic Roadmap\n\n## 📝 משימות פתוחות\n"

    # 2. סינון משימות שכבר מופיעות ב-Roadmap
    unique_tasks = []
    for task in new_tasks:
        if task not in existing_content:
            unique_tasks.append(f"- [ ] {task} (נוסף ב-{now})")

    if not unique_tasks:
        print("ℹ️ [Roadmap] No new unique tasks to add.")
        return

    # 3. הזרקת המשימות החדשות מתחת לכותרת
    task_block = "\n".join(unique_tasks) + "\n"
    if "## 📝 משימות פתוחות" in existing_content:
        updated_content = existing_content.replace("## 📝 משימות פתוחות\n", f"## 📝 משימות פתוחות\n{task_block}")
    else:
        updated_content = existing_content + f"\n## 📝 משימות פתוחות\n{task_block}"

    with open(roadmap_file, "w", encoding="utf-8") as f:
        f.write(updated_content)
    
    print(f"✅ [Roadmap] {len(unique_tasks)} new tasks injected into ROADMAP.md")
# =====

# =====
def propose_improvements(root_memory):
    """(Proactive) סורק את המערכת ומציע שיפורים עתידיים כ-Issues בגיטהאב"""
    print("[Root Proactive] Brainstorming future improvements...")
    target_lang = getattr(Config, 'UI_LANGUAGE', 'English')
    proposed_titles = []
    
    try:
        context_results = root_memory.search_memory("project architecture constraints roadmap features", top_k=5)
        context = ""
        
        if context_results:
            for item in context_results:
                if isinstance(item, tuple) and len(item) == 2:
                    context += f"- {item[1].get('text', '')}\n"

        prompt = f"""Based on context: {context}
        Suggest 1-2 technical improvements. Return JSON object with 'tasks' (array of 'title' and 'description').
        Write in {target_lang}."""

        response = client.chat.completions.create(
            model=Config.MODEL,
            messages=[{"role": "user", "content": prompt}],
            response_format={"type": "json_object"}
        )
        
        result = json.loads(response.choices[0].message.content.strip())
        tasks = result.get("tasks", [])
        
        for task in tasks:
            title = task.get('title')
            proposed_titles.append(title)
            create_github_issue(
                title=f"🤖 Root Suggestion: {title}",
                body=task.get('description') + "\n\n---\n*Proactively generated by Root OS.*",
                labels=["root-task", "automated-suggestion"]
            )
            
        return proposed_titles
    except Exception as e:
        print(f"⚠️ [Root Proactive] Failed: {e}")
        return proposed_titles
# =====
