#!/usr/bin/env python3
# =====
import os
from datetime import datetime
from config import Config
# =====

# =====
def update_manifest(analysis, critic_feedback=None):
    """(לוח מחיק) מנקה את ROOT.md וכותב אותו מחדש מאפס למניעת כפילויות"""
    now_str = datetime.now().strftime('%d/%m/%Y %H:%M')
    
    # הכנת התוכן המעוצב
    content_blocks = [
        f"> **Status:** 🟢 מעודכן ל-{now_str}\n",
        f"> \n",
        f"> **ניתוח אחרון:**\n"
    ]
    
    for part in analysis.split('\n'):
        if part.strip():
            prefix = "" if part.strip().startswith(('*', '-', '>')) else "* "
            content_blocks.append(f"> {prefix}{part.strip()}\n")
            
    if critic_feedback and not critic_feedback.startswith("PASS"):
        content_blocks.append(f"> \n")
        content_blocks.append(f"> **⚠️ התראת ארכיטקט (Critic):**\n")
        for part in critic_feedback.split('\n'):
            if part.strip():
                prefix = "" if part.strip().startswith(('*', '-', '>')) else "* "
                content_blocks.append(f"> {prefix}{part.strip()}\n")
    content_blocks.append(f">\n")

    # 🔴 הפתרון של הלוח המחיק: תמיד פותחים במצב 'w' ודורסים את הישן
    print(f"[Root] Regenerating {Config.MANIFEST_PATH} cleanly...")
    with open(Config.MANIFEST_PATH, "w", encoding="utf-8") as f:
        f.write("# 🌳 Root Project Manifest\n\n")
        f.write("## 🎯 Current Architecture Context\n")
        f.writelines(content_blocks)
        f.write("\n---\n*Generated by Root Agentic OS*\n")
        
    print("✅ [Root] ROOT.md regenerated fresh (Overwrite method applied).")
# =====
